# Generated by Django 5.2.1 on 2025-05-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tareas_descripcion_alter_tareas_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='estado',
            field=models.CharField(choices=[('C', 'Completada'), ('P', 'Pendiente')], default='P', max_length=1),
        ),
    ]
