services:
  - type: web
    name: backend-django
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: SECRET_KEY
        value: tu-secret
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: backend-django.onrender.com
